#ifndef INC_APP_CONFIG_H_
#define INC_APP_CONFIG_H_

#define CONFIG_SYSTEMVIEW 1
#define CONFIG_SYSTEMVIEW_MAX_PRIO 40

#define INIT_TASK_PRIO (CONFIG_SYSTEMVIEW_MAX_PRIO - 1)

#endif /* INC_APP_CONFIG_H_ */
